version: "3.8"

services:
  ##### DATABASE #####
  postgres:
    image: postgres:13.3-alpine
    container_name: db_postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  ##### pgAdmin #####
  pgadmin:
    image: dpage/pgadmin4:5.5
    container_name: app_pgadmin
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 8055:80
    volumes:
      - pgadmin_data:/var/lib/pgAdmin
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
